const DEFAULT_BRIDGE_HOST = 'localhost'
const DEFAULT_BRIDGE_PORT = 8080
const DEFAULT_REDIS_HOST = 'localhost'
const DEFAULT_REDIS_PORT = 6379
const DEFAULT_NODE_ID = '00000000-0000-0000-0000-000000000000'

const config = {
  BRIDGE_HOST: process.env.BRIDGE_HOST || DEFAULT_BRIDGE_HOST,
  BRIDGE_PORT: process.env.BRIDGE_PORT || DEFAULT_BRIDGE_PORT,
  REDIS_HOST: process.env.REDIS_HOST || DEFAULT_REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT || DEFAULT_REDIS_PORT,
  NODE_ID: process.env.NODE_ID || DEFAULT_NODE_ID
}

export default config
